name: Scrape Airbnb Hosts

on:
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm i

      - name: Run scraper
        run: npm start

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: airbnb-scrape-output
          path: |
            output/results.csv
            output/debug/**
          if-no-files-found: warn
